Improve caching behaviour
pl3xgaming/Pl3xMap pull request #71
Opened 2021-08-01 21:02 UTC by JLyne

This PR attempts to improve Pl3xmap's leverage of browser caching. Currently Pl3xmap adds cache-busting query strings to all tile URLs, which ensures the tiles are up to date but also prevents browsers from caching the images effectively. This combined with the regular redrawing of the map's `TileLayer` causes excessive bandwidth usage via repeated downloads of the same image.

This PR addresses this problem in 3 ways:

1. **Adding cache headers to the integrated server response**
   Tiles requested from the integrated server will now have a `Cache-Control: max-age=0, must-revalidate, no-cache` header applied. `must-revalidate/no-cache` will instruct the browser to ask the server about new versions of the image on subsequent loads, while `max-age=0` will ensure this happens immediately by making the image stale straight away.

   When combined with the existing `Last-modified` and `Etag` headers, browsers will now send `If-modified-since` and `If-none-match` headers on subsequent requests for the same tile URL, allowing the server to respond with a `304 Not Modified` if the tile hasn't changed, allowing the browser to use its existing copy without having to download it again. 
2. **Avoiding cache-busting query strings on tile URLs**
  The approach in point 1 will only work if the tile URLs remains the same, which requires the existing random numbers appended to tile URLs to be removed. On its own this prevents tiles from updating when the `TileLayer`  is redrawn, as there is no longer a URL change to cause it to do so.
3. **Use the fetch API for retrieving tiles**
  The stock `TileLayer` has been extended to use the Fetch API for retrieving tile image data, instead of relying on the browser to do so via setting an `<img>` src. This resolves the problem introduced in point 2 as we no longer depend on the browser deciding to re-request images, and fetch will by default respect cache headers and return a cached response where appropriate.

### Results
The result is significantly reduced bandwidth usage, whilst retaining the ability for tiles to update when they have changed. 

Build 155 after 1 minute idle
![image](https://user-images.githubusercontent.com/4615316/127783311-b027d993-34bc-4c07-a58d-d94ab057278d.png)

PR after 1 minute idle
![image](https://user-images.githubusercontent.com/4615316/127783437-9981fa22-3717-4554-b906-3b37a2825496.png)
The additional requests are due to object URLs showing up separately

### Caveats
There are some downsides to this approach:

1. Tile creation is significantly slower with fetch than with plain images, taking twice as long in my testing.
2. External web servers need to be configured appropriately to avoid tiles being cached for too long.

The first issue is noticeable during performance testing, but may not be for the average user. If it does become a problem however the fetch could be moved to a web worker, which brings performance back to the previous level. I considered that out of scope for this PR though.

The second issue can be solved by documenting an appropriate external server configuration, which would be to ensure tile images have a  `Cache-Control: max-age=0, must-revalidate, no-cache`/`Last-modified`/`Etag` headers.

2021-08-01 21:34 UTC, notOM3GA requested changes

2021-08-01 21:34 UTC, notOM3GA commented on plugin/src/main/resources/web/js/modules/Pl3xmapTileLayer.js
> +});
add newline at end of file

2021-08-01 21:34 UTC, notOM3GA commented on plugin/src/main/resources/web/js/modules/LayerControl.js
> +import {Pl3xmapTileLayer} from "./Pl3xmapTileLayer.js";
minor style
```suggestion
import { Pl3xmapTileLayer } from './Pl3xmapTileLayer.js';
```

2021-08-02 09:13 UTC, granny approved these changes
LGTM

> External web servers need to be configured appropriately to avoid tiles being cached for too long.

> The second issue can be solved by documenting an appropriate external server configuration, which would be to ensure tile images have `Cache-Control: max-age=0, must-revalidate, no-cache`/`Last-modified`/`Etag` headers.

We already have a page dedicated to setting up an external server (Apache & Nginx) with basic configuration; [Internal vs External Web Server](https://github.com/pl3xgaming/Pl3xMap/wiki/Internal-vs-External-Web-Server). I don't have experience using either of them so it would require someone else to handle updating the Apache/Nginx sections.

CC: @KoxSosen @Encode42

2021-08-04 17:44 UTC, notOM3GA approved these changes

2021-08-06 06:36 UTC, BillyGalbreath approved these changes
Looks good to me ^_^

2021-08-06 06:41 UTC, merged